# Postgres
spring.application.name=MyProject
spring.datasource.url=jdbc:postgresql://localhost:5432/myProject
spring.datasource.username=postgres
spring.datasource.password=amirr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
## Oracle
#spring.datasource.oracle.url=jdbc:oracle:thin:@//oracle_host:1521/service_name
#spring.datasource.oracle.username=oracle_username
#spring.datasource.oracle.password=oracle_password
#spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver